name: run-pre-commit-checks
run-name: Running pre-commit checks against all files
on: [push, pull_request]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install Markdownlint
        run: npm install -g markdownlint-cli

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
